#pragma once
enum
{
     CS_ALIVE = 0 , CS_DEAD , CS_SPAWNING , CS_LAGGED , CS_EDITING , CS_SPECTATOR
};

enum
{
     PHYS_FLOAT = 0 , PHYS_FALL , PHYS_SLIDE , PHYS_SLOPE , PHYS_FLOOR , PHYS_STEP_UP , PHYS_STEP_DOWN , PHYS_BOUNCE
};

enum
{
     ENT_PLAYER = 0 , ENT_AI , ENT_INANIMATE , ENT_CAMERA , ENT_BOUNCE
};

enum
{
     COLLIDE_AABB = 0 , COLLIDE_OBB , COLLIDE_ELLIPSE
};

enum
{
     GUN_FIST = 0 , GUN_SG , GUN_CG , GUN_RL , GUN_RIFLE , GUN_GL , GUN_PISTOL , GUN_FIREBALL , GUN_ICEBALL , GUN_SLIMEBALL , GUN_BITE , GUN_BARREL , NUMGUNS
};
enum
{
     A_BLUE , A_GREEN , A_YELLOW
};  
enum
{
     M_NONE = 0 , M_SEARCH , M_HOME , M_ATTACKING , M_PAIN , M_SLEEP , M_AIMING
};  